### ISSUE TITLE
Implement the serial listener code according to the specifications

### ISSUE THREAD

**Issue by sadmansk** [uwnrg/sam#1]
> Mirror of https://github.com/uwnrg/minotaur-cpp/issues/18

Specifications:
Baud rate has to be set to ``9600``. And the data recieived by the arduino should be a byte array of size 4, where:
```
byte[0]: 1 for up,    -1 for down, 0 for no movement on y-axis
byte[1]: 1 for right, -1 for left, 0 for no movement on x-axis
byte[2]: (in seconds) how long the command should be kept on
byte[3]: speed (unit yet to be determined)
```

**Comment by aneedalie** [comment]
Closing this because it's out of date. Will add new issues as we uncover them at the lab meeting.
